spring:
  application:
    name: SCW-REGISTER
 
server:
  port: 8761
  
eureka:
  instance:
    hostname: localhost
    
  client:
    register-with-eureka: false #本身就是服务器，不需要将自己注册到eureka服务器中
    fetch-registry: false #是否从eureka中获取信息,本身就是服务器不需要获取
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/